export const abi = [
  {
    inputs: [],
    name: 'name',
    outputs: [{ type: 'string' }],
    type: 'function',
    stateMutability: 'view',
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [{ type: 'string' }],
    type: 'function',
    stateMutability: 'view',
  },
  {
    inputs: [],
    name: 'decimals',
    outputs: [{ type: 'uint8' }],
    type: 'function',
    stateMutability: 'view',
  },
  {
    inputs: [],
    name: 'totalSupply',
    outputs: [{ type: 'uint256' }],
    type: 'function',
    stateMutability: 'view',
  },
  {
    inputs: [{ type: 'address' }],
    name: 'balanceOf',
    outputs: [{ type: 'uint256' }],
    type: 'function',
    stateMutability: 'view',
  },
  {
    inputs: [{ type: 'address' }, { type: 'address' }],
    name: 'allowance',
    outputs: [{ type: 'uint256' }],
    type: 'function',
    stateMutability: 'view',
  },
  {
    inputs: [{ type: 'address' }, { type: 'uint256' }],
    name: 'approve',
    outputs: [{ type: 'bool' }],
    type: 'function',
    stateMutability: 'nonpayable',
  },
  {
    inputs: [{ type: 'address' }, { type: 'uint256' }],
    name: 'transfer',
    outputs: [{ type: 'bool' }],
    type: 'function',
    stateMutability: 'nonpayable',
  },
  {
    inputs: [{ type: 'address' }, { type: 'address' }, { type: 'uint256' }],
    name: 'transferFrom',
    outputs: [{ type: 'bool' }],
    type: 'function',
    stateMutability: 'nonpayable',
  },
] as const
